### ISSUE TITLE
script / guide to sideload

### ISSUE THREAD

**Issue by kambala-decapitator** [kambala-decapitator/vcmi#19]
also AltStore

**Comment by matakko** [comment]
very good idea, altstore. very active community.

**Comment by kambala-decapitator** [comment]
@hjsm23 afaik AltStore has a bug that it doesn't sign embedded dynamic libraries (PR for that was still open last time I checked), without that VCMI wouldn't work in the current state. I guess it's possible to build all libs as static (like android does) to workaround that.

Btw do you have experience with AltStore? Do you know if it's possible to pass custom entitlements? (required to play VCMI in SP)

**Comment by matakko** [comment]
Hey Kambala unfortunately am a newbie on github/coding and ios , i follow actively DolphinIos project and altstore . 
They is a lot of new feature in the roadmap of alstore.
Ive looked some PR for signing the dynamic library do you refer to this issue: https://github.com/rileytestut/AltStore/issues/159 ?
will try to see further, asking around , ill start to read also the all the issues you posted see if i can help  in a way.

**Comment by kambala-decapitator** [comment]
> Ive looked some PR for signing the dynamic library do you refer to this issue: [rileytestut/AltStore#159](https://github.com/rileytestut/AltStore/issues/159) ?

Yes, that's it.

> will try to see further, asking around , ill start to read also the all the issues you posted see if i can help in a way.

That'd be great, thank you!
