### ISSUE TITLE
chat text being entered is invisible (white) in dark mode

### ISSUE THREAD

**Issue by kambala-decapitator** [kambala-decapitator/vcmi#45]

**Comment by matakko** [comment]
Hello,

I don’t know if it’s related but my text doesn’t register always when I’m trying to type for saving a game.

I use dark mode on iOS so maybe linked .

When I try to save, the iOS keyboard show up but when typing nothing register , also the underscore sign doesn’t show in the text field in the game. If I lower the iOS keyboard and make it re-appear multiple times , it will let me register what I’m typing with the underscore sign in the text field .

**Comment by kambala-decapitator** [comment]
@hjsm23 it's a different issue and should've been fixed in the "RC" build (I guess you're still using beta). Could you test the RC build? https://github.com/vcmi/vcmi/suites/7857731842/artifacts/333035339
