### ISSUE TITLE
Crash with custom campaign menu 

### ISSUE THREAD

**Issue by matakko** [kambala-decapitator/vcmi#46]
Hello,

I’ve notice that custom campaign menu can bring crash , I didn’t tried to import a custom campaign.

-Here is how to reproduce: new game > campaign > custom > back = crash 

-expected : after pressing back it should bring us back to the campaign selection menu .

**Comment by kambala-decapitator** [comment]
Most probably this is a core issue. Have you checked the same in desktop version?

Or maybe it's iOS-specific indeed. I'll check after rebasing to the latest version.

Thanks for the report!
