### ISSUE TITLE
accepting LAN connection works only in simulator

### ISSUE THREAD

**Issue by kambala-decapitator** [kambala-decapitator/vcmi#5]
server needs to send fake request to a LAN address to make system LAN permission appear

- https://github.com/hayderimran7/advanced-socket-programming/blob/master/ping.c
- https://www.geeksforgeeks.org/ping-in-c/
- https://developer.apple.com/library/archive/samplecode/SimplePing/Listings/Common_SimplePing_m.html#//apple_ref/doc/uid/DTS10000716-Common_SimplePing_m-DontLinkElementID_4

**Comment by kambala-decapitator** [comment]
https://developer.apple.com/forums/thread/664775

**Comment by matakko** [comment]
https://github.com/osy/Jitterbug/commit/d701acf49dc159fc5d5dc19772424a1f19b64f56 
"we can fake packets through
a custom VPN connection created to modify the IP packets to pretend we are
from another device."
Is it close to what we need to achieve ?

**Comment by kambala-decapitator** [comment]
> https://developer.apple.com/forums/thread/664775

I hope that this would work (code is from an apple engineer) and an overkill of creating VPN connection won't be needed.

**Comment by kambala-decapitator** [comment]
I got the following results with the LAN alert trigger code mentioned above (now I'm not even sure that it's actually required), seems there's some extra setup work needed on iOS to accept connections from other iOS clients...

Server \ client | macOS | iOS 12 | iOS 15
-- | -- | -- | --
macOS 11 |   | + | +
iOS 12 | - |   | -
iOS 15 | + | - | -

**Comment by kambala-decapitator** [comment]
after some investigation it actually seems an issue with my LAN for wireless-wireless connections, as I can't even access a local http server from an iOS device when it's running over wi-fi
